#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 5a32cbf7-10aa-4e36-ad53-99915107fb74
# Source File: Services.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
LwQAAB+LCAAAAAAABABllEmLq1oUheeC/6G4U+GqSUwU6hYY+97YROPMmBNjd+z1mF9/i3o8ePD2
aK+12KPFtz89kLULGDYxndKP72UsWvjn1/43/esLxz4+Pp2hyAuY1nJRAzttwJcPhqXIwPi7G5+f
5P/inyO5HZovi0ZIaIp9hzSeFxxR4P+ZMy8+am52diV/ec3swHm7Ipay0UmMSZN1fab1667QhYnJ
Bp1CZtFYJTqql+7IvXHsJql1Ilve1Z8kWRjfsCTAG9kuSS2shAxwPnLP9NqTavNix4N/Vht6E2sI
I6prOPkJQMqP/ZFQHvPm4VgbUMJG28a5OsKIPFimv64myi3h7GdahNrDZirpU/Ps2jnyoqGB977S
ewbup9F5uPQp9q1WYhSyIGsLx+JwaYzkgG4pUGv1rGQpE1ttfLFS27yp78Ax18nRKP/lyI8mlzrv
8gre3Nma98Tevu8rooXOhWeBZ/gmjrmF7ORPviV9Kottdm9b2Wa+O06uM66XT1M7UyE9vMN10EWK
zAbpPiOFlqiUSFhjJk8PLg4GAOuHxlxwTHTLhsi8ujYt3U2UOG0jOGiCmAQvSrElKfPlWETbErg7
r9aR4fe0uw5rlJhTQXRHifACWWVzi4ZtjmMJzdTxdfi3Ytlns5s/sXqh8KMeEBVNrOgdTjD3BoFI
ZZE8HhpfP8JbJjF6kKlGd+DNSY61plVxrLB3b6QzdPes27WqROrl8JEGamZbc1heclHXGMuVlxeS
0CsTqotYFsqKxFpAQlFUp9Ode7aSXwfnu4tjAvkKxSfbh2NvvWJbkyvnuJR17XsIIbVgImV3NYdl
MHSFqbbc7nagu25scgmiTIBmuLqD66SqmSRzhmORmsRNYqdtucKlbGGZa5CCOpAEEOQdv7OeEueF
bZo/jQtw+ouvUjeDKiv6vuZe3z/4WwebPZcjNeBwLKVafTsT6tCqUtiPVdh0s5hVt8pL0z4Kpbse
NpUxeuMCjuGti1c7cHSg3w4L9EsRDbVDdCf3W4+FhGM7w618AUzQjKJo5m/2btoeD7swmn0QhyLz
jDs55ubr/pjZ0tTfWQrelR1aWIJ3JbjpRJr530D++SR/gP1Blx9H0NzrAowf5LfzSf73QXz9BfA0
VQcvBAAA#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2020 v5.7.174
     Generated on:       01.05.2020 15:33
     Generated by:       Thomas Meyer
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2020
#>


#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-Services_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$form1 = New-Object 'System.Windows.Forms.Form'
	$label1 = New-Object 'System.Windows.Forms.Label'
	$bReload = New-Object 'System.Windows.Forms.Button'
	$cbStarting = New-Object 'System.Windows.Forms.CheckBox'
	$cbStopping = New-Object 'System.Windows.Forms.CheckBox'
	$cbRunning = New-Object 'System.Windows.Forms.CheckBox'
	$cbStopped = New-Object 'System.Windows.Forms.CheckBox'
	$pServices = New-Object 'System.Windows.Forms.Panel'
	$lblService = New-Object 'System.Windows.Forms.Label'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	$services = "";
	
	function GetService($status)
	{
		
		switch ($status)
		{
			"stoping"
			{
				$services = Get-Service | Where-Object { $_.status -eq "stoping" };
				break;
			}
			"starting"
			{
				$services = Get-Service | Where-Object { $_.status -eq "starting" };
				break;
			}
			"running"
			{
				$services = Get-Service | Where-Object { $_.status -eq "running" };
				break;
			}
			"stopped"
			{
				$services = Get-Service | Where-Object { $_.status -eq "stopped" };
				break;
			}
			default
			{
				$services = Get-Service;
				break;
			}
		}
		return $services;
		
	}
	$form1_Load = {
		#TODO: Initialize Form Controls here
		$label1.Text = 0;
	}
	
	$bReload_Click={
		#TODO: Place custom script here	
		if ($cbRunning.Checked)
		{
			$services += GetService("running");
			Write-Host $services;
		}
		if ($cbStarting.Checked)
		{
			$services += GetService("starting");
			Write-Host $services;
		}
		if ($cbStopped.Checked)
		{
			$services += GetService("stopped");
			Write-Host $services;
		}
		if ($cbStopping.Checked)
		{
			$services += GetService("stoping");
			Write-Host $services;
		}
		$pServices.Controls.Clear();
		$pServices.AutoScroll = $false;
		$pServices.HorizontalScroll.Enabled = $false;
		$pServices.HorizontalScroll.Visible = $false;
		$pServices.HorizontalScroll.Maximum = 0;
		$pServices.AutoScroll = $true;
		$x = 12;
		$z = 12;
		for ($i = 0; $i -lt $services.Length; $i++)
		{
			$labelTaux = New-Object System.Windows.Forms.Label;
			$labelTaux.AutoSize = $true;
			$labelTaux.Location = New-Object System.Drawing.Point(250, $z);
			$labelTaux.Name = "lblStatus";
			$labelTaux.Size = New-Object System.Drawing.Size(21, 13);
			$labelTaux.TabIndex = 5;
			$labelTaux.Text = $services[$i].status
			$label = New-Object System.Windows.Forms.Label;
			$label.AutoSize = $true;
			$label.Location = New-Object System.Drawing.Point(4, $x);
			$label.Name = "lblNameService";
			$label.Size = New-Object System.Drawing.Size(75, 13);
			$label.TabIndex = 4;
			$label.Text = $services[$i].Name;
			
			
			$pServices.Controls.Add($labelTaux);
			$pServices.Controls.Add($label);
			$x += 43;
			$z += 43;
			$label1.Text = 1;
			
		}
		
	}
	
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$form1.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$bReload.remove_Click($bReload_Click)
			$form1.remove_Load($form1_Load)
			$form1.remove_Load($Form_StateCorrection_Load)
			$form1.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$form1.SuspendLayout()
	#
	# form1
	#
	$form1.Controls.Add($label1)
	$form1.Controls.Add($bReload)
	$form1.Controls.Add($cbStarting)
	$form1.Controls.Add($cbStopping)
	$form1.Controls.Add($cbRunning)
	$form1.Controls.Add($cbStopped)
	$form1.Controls.Add($pServices)
	$form1.Controls.Add($lblService)
	$form1.AutoScaleDimensions = '6, 13'
	$form1.AutoScaleMode = 'Font'
	$form1.ClientSize = '588, 421'
	$form1.Name = 'form1'
	$form1.Text = 'Form'
	$form1.add_Load($form1_Load)
	#
	# label1
	#
	$label1.AutoSize = $True
	$label1.Location = '466, 121'
	$label1.Name = 'label1'
	$label1.Size = '35, 17'
	$label1.TabIndex = 17
	$label1.Text = 'label1'
	$label1.UseCompatibleTextRendering = $True
	$label1.Visible = $False
	#
	# bReload
	#
	$bReload.Location = '372, 45'
	$bReload.Name = 'bReload'
	$bReload.Size = '75, 23'
	$bReload.TabIndex = 16
	$bReload.Text = 'recherche'
	$bReload.UseCompatibleTextRendering = $True
	$bReload.UseVisualStyleBackColor = $True
	$bReload.add_Click($bReload_Click)
	#
	# cbStarting
	#
	$cbStarting.AutoSize = $True
	$cbStarting.Location = '304, 45'
	$cbStarting.Name = 'cbStarting'
	$cbStarting.Size = '62, 17'
	$cbStarting.TabIndex = 15
	$cbStarting.Text = 'Starting'
	$cbStarting.UseVisualStyleBackColor = $True
	#
	# cbStopping
	#
	$cbStopping.AutoSize = $True
	$cbStopping.Location = '230, 45'
	$cbStopping.Name = 'cbStopping'
	$cbStopping.Size = '68, 17'
	$cbStopping.TabIndex = 14
	$cbStopping.Text = 'Stopping'
	$cbStopping.UseVisualStyleBackColor = $True
	#
	# cbRunning
	#
	$cbRunning.AutoSize = $True
	$cbRunning.Location = '86, 45'
	$cbRunning.Name = 'cbRunning'
	$cbRunning.Size = '66, 17'
	$cbRunning.TabIndex = 13
	$cbRunning.Text = 'Running'
	$cbRunning.UseVisualStyleBackColor = $True
	#
	# cbStopped
	#
	$cbStopped.AutoSize = $True
	$cbStopped.Location = '158, 45'
	$cbStopped.Name = 'cbStopped'
	$cbStopped.Size = '66, 17'
	$cbStopped.TabIndex = 12
	$cbStopped.Text = 'Stopped'
	$cbStopped.UseVisualStyleBackColor = $True
	#
	# pServices
	#
	$pServices.BackColor = 'Silver'
	$pServices.Location = '34, 68'
	$pServices.Name = 'pServices'
	$pServices.Size = '332, 148'
	$pServices.TabIndex = 11
	#
	# lblService
	#
	$lblService.Location = '31, 45'
	$lblService.Name = 'lblService'
	$lblService.Size = '65, 17'
	$lblService.TabIndex = 10
	$lblService.Text = 'Services :'
	$form1.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $form1.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$form1.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$form1.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $form1.ShowDialog()

} #End Function

#Call the form
Show-Services_psf | Out-Null
